environment:
  
  matrix:
    - PYTHON_VERSION: "3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
    - x64
clone_depth: 1
shallow_clone: true
build: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\pyemu'

init:
  - echo %PYTHON_VERSION% %CONDA_INSTALL_LOCN%

install:
  - set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%;
  - set PYTHONUNBUFFERED=1
  # for msinttypes and newer stuff
  - conda config --set always_yes true
  - conda update conda
  - conda update --all
  - conda config --set show_channel_urls yes
  - conda config --prepend channels conda-forge
  - conda info -a

  - conda install --yes python=%PYTHON_VERSION% pip numpy scipy pandas nose matplotlib jupyter notebook cartopy
  - pip install coveralls
  - pip install pyshp
  - pip install nose-timer
  - pip install git+https://github.com/modflowpy/flopy.git@develop
  - pip install git+https://github.com/jtwhite79/pyemu.git@develop
  # Show the installed packages + versions
  - conda list

test_script:
  - #cd benchmarks
  - set PATH=..\..\..\test_bin\win;%PATH;
  - nosetests -v --with-id --nocapture --with-timer -w benchmarks ies_test:test_chenoliver
  - #cd ..

after_test:
 - echo "done"
matrix:
  fast_finish: true